trigger: none

resources:
  pipelines:
  - pipeline: CIFrontendPipeline
    source: 'Release - CLIENT'
    trigger:
      branches:
      - main

jobs:
  - deployment: deployErniPbaFrontend
    displayName: 'Deploy ERNI PBA Frontend'
    environment: ERNI PBA Azure
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'specific'
                project: 'a8f9c350-6687-4de5-a5b1-dd543f183854'
                definition: '602'
                specificBuildWithTriggering: true
                buildVersionToDownload: 'latest'
                artifactName: 'erni-pba-release'
                targetPath: '$(Pipeline.Workspace)'

            - task: AzureStaticWebApp@0
              inputs:
                workingDirectory: '$(Pipeline.Workspace)'
                app_location: ''
                skip_app_build: true
                skip_api_build: true
                azure_static_web_apps_api_token: '$(DeployToken)'
