trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: '10.x'

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: 'ci'
    workingDir: 'client/'

# - task: Npm@1
#   displayName: 'npm lint'
#   inputs:
#     command: 'custom'
#     workingDir: 'client/'
#     customCommand: 'run lint'

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: 'custom'
    workingDir: 'client/'
    customCommand: 'run build -- --prod'
